import assert from "node:assert/strict";
import test from "node:test";

import {
  KUROME_PROTOTYPE_TUNING,
  advanceKuromeTracking,
  beginKuromeTracking,
  createKuromeTrackingRuntime,
  kuromeEmergencyEvadePlan,
  resolveKuromeBeam,
} from "../app/kuromeBoss.js";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const human = (overrides = {}) => ({
  id: 1,
  side: "human",
  hp: 100,
  combatReady: true,
  targetable: true,
  x: 320,
  y: 270,
  lane: 1,
  bodyRadius: 11,
  ...overrides,
});

test("tracking follows during the readable window, then locks deterministically", () => {
  const started = beginKuromeTracking(human());
  assert.equal(started.ok, true);
  const following = advanceKuromeTracking(started.runtime, .3, human({ x: 350, y: 230, lane: 0 }));
  assert.equal(following.runtime.phase, "tracking");
  assert.equal(following.runtime.targetX, 350);
  assert.equal(following.runtime.targetY, 230);
  const locked = advanceKuromeTracking(following.runtime, .6, human({ x: 400, y: 330, lane: 2 }));
  assert.equal(locked.runtime.phase, "locked");
  assert.equal(locked.runtime.targetX, 350);
  assert.equal(locked.runtime.targetY, 230);
  const fired = advanceKuromeTracking(locked.runtime, 1);
  assert.equal(fired.fired, true);
  assert.equal(fired.runtime.phase, "firing");
});

test("beam hits a held target and misses a target that leaves the locked ray", () => {
  const boss = { x: 760, y: 270 };
  const firing = { phase: "firing", targetX: 320, targetY: 270 };
  assert.deepEqual(
    resolveKuromeBeam({ boss, runtime: firing, candidates: [human()] }).hits,
    ["1"],
  );
  assert.deepEqual(
    resolveKuromeBeam({
      boss,
      runtime: firing,
      candidates: [human({ y: 365, lane: 2 })],
    }).hits,
    [],
  );
});

test("one-tap emergency evade locks the old ray and chooses a different far lane", () => {
  const target = human();
  const tracking = beginKuromeTracking(target).runtime;
  const planned = kuromeEmergencyEvadePlan({
    runtime: tracking,
    target,
    tap: { x: target.x + 18, y: target.y - 32 },
    laneCenters: [240, 285, 325],
  });
  assert.equal(planned.ok, true);
  assert.equal(planned.lane, 2);
  assert.equal(planned.runtime.phase, "locked");
  assert.equal(planned.runtime.targetX, target.x);
  assert.equal(planned.runtime.targetY, target.y);
  const nextTick = advanceKuromeTracking(
    planned.runtime,
    .05,
    human({ y: 325, lane: planned.lane }),
  );
  assert.equal(nextTick.runtime.phase, "locked");
  assert.equal(nextTick.runtime.targetY, target.y);
  const fired = advanceKuromeTracking(nextTick.runtime, 1);
  assert.deepEqual(resolveKuromeBeam({
    boss: { x: 760, y: 270 },
    runtime: fired.runtime,
    candidates: [human({ y: 325, lane: planned.lane })],
  }).hits, []);
  assert.equal(kuromeEmergencyEvadePlan({
    runtime: tracking,
    target,
    tap: { x: 900, y: 20 },
  }).ok, false);
});

test("invalid targets cannot start and the full state machine terminates", () => {
  assert.equal(beginKuromeTracking(human({ hp: 0 })).ok, false);
  let runtime = beginKuromeTracking(human()).runtime;
  let fired = 0;
  let recovered = 0;
  for (let index = 0; index < 20 && runtime.phase !== "idle"; index += 1) {
    const step = advanceKuromeTracking(runtime, .2, human());
    runtime = step.runtime;
    if (step.fired) fired += 1;
    if (step.recovered) recovered += 1;
  }
  assert.deepEqual(runtime, createKuromeTrackingRuntime());
  assert.equal(fired, 1);
  assert.equal(recovered, 1);
  assert.ok(KUROME_PROTOTYPE_TUNING.warningSeconds > KUROME_PROTOTYPE_TUNING.trackingSeconds);
});

test("prototype ledger fixes the exact generated bytes, dimensions, and builder provenance", async () => {
  const ledger = JSON.parse(await readFile(
    path.join(root, "docs/BOSS_PROTOTYPE_ASSETS_0.9.0.json"),
    "utf8",
  ));
  assert.equal(ledger.status, "producer-approved");
  assert.equal(ledger.generatedAssets.length, 3);
  for (const asset of ledger.generatedAssets) {
    const absolutePath = path.join(root, asset.path);
    const bytes = await readFile(absolutePath);
    const metadata = await sharp(bytes).metadata();
    assert.equal(createHash("sha256").update(bytes).digest("hex"), asset.sha256);
    assert.equal(bytes.length, asset.bytes);
    assert.deepEqual([metadata.width, metadata.height], asset.dimensions);
    assert.equal(asset.generatedBy, "scripts/build-v090-kurome-prototype-assets.mjs");
    assert.ok(asset.derivedFrom.every((sourcePath) => ledger.sourceAssets.some(({ path: candidate }) => candidate === sourcePath)));
  }
});
