import assert from 'node:assert/strict';
import test from 'node:test';
import { V100_KUMAVERSON_GUARD_ART, v100KumaversonGuardPose, v100RenderedKumaversonPanSocket } from '../app/v100KumaversonPresentation.js';
import { drawV100ContactQueue, queueV100GuardContact } from '../app/v100CombatVfx.js';
import { MANUAL_ABILITY_REGISTRY, createManualAbilityRuntime, beginManualAbility, advanceManualAbility } from '../app/manualAbilities.js';

test('Kuma guard phases follow the real manual ability runtime',()=>{let r=createManualAbilityRuntime('kumaverson');assert.equal(r.phase,'ready');r=beginManualAbility(r,{x:1,y:0}).runtime;assert.equal(r.phase,'windup');assert.equal(v100KumaversonGuardPose(r,MANUAL_ABILITY_REGISTRY.kumaverson,0),'idle');r=advanceManualAbility(r,.35).runtime;assert.equal(r.phase,'active');assert.equal(v100KumaversonGuardPose(r,MANUAL_ABILITY_REGISTRY.kumaverson,0),'guard');assert.equal(v100KumaversonGuardPose(r,MANUAL_ABILITY_REGISTRY.kumaverson,.06),'hit');assert.equal(v100KumaversonGuardPose(r,MANUAL_ABILITY_REGISTRY.kumaverson,0,{moving:true} ),null);r=advanceManualAbility(r,6).runtime;assert.equal(r.phase,'recovery');assert.equal(v100KumaversonGuardPose(r,MANUAL_ABILITY_REGISTRY.kumaverson,0),'guard');r=advanceManualAbility(r,.18).runtime;assert.ok(['cooldown','ready'].includes(r.phase));});
test('Kuma pan socket mirrors the actual left flip contract',()=>{const a=v100RenderedKumaversonPanSocket({x:240,y:432,size:{w:480,h:448},direction:'right',flipX:false}),b=v100RenderedKumaversonPanSocket({x:240,y:432,size:{w:480,h:448},direction:'left',flipX:true});assert.ok(Math.abs(a.x-303.613)<.01);assert.ok(Math.abs(b.x-176.387)<.01);assert.equal(a.y,b.y);assert.equal(V100_KUMAVERSON_GUARD_ART.authoredCell.w,480);});
test('Kuma contact is fail-closed until one real socket resolves, then expires at 160ms',()=>{const w={time:1,definition:{missionConfig:{v100StageNumber:3}}},owner={id:7,side:'human',kind:'kumaverson',hp:10,x:2,manualAbility:{phase:'active',activationId:1,target:{direction:1}}},hit={owner,attacker:{side:'zombie',x:3},incomingDamage:2,x:3,y:4};const ctx={save(){},restore(){},translate(){this.n=(this.n||0)+1},drawImage(){}};const objects={'v100-metal-contact':{complete:true,naturalWidth:1536}};assert.ok(queueV100GuardContact(w,hit));drawV100ContactQueue(ctx,objects,w);assert.equal(ctx.n,undefined);drawV100ContactQueue(ctx,objects,w,()=>({x:9,y:8}));assert.equal(ctx.n,1);w.time+=.17;drawV100ContactQueue(ctx,objects,w,()=>({x:9,y:8}));assert.equal(ctx.n,1);});
