const DEFAULT_MAX_BYTES = 8 * 1024 * 1024;
const DEFAULT_MAX_ENTRIES = 128;
const finite = (value) => typeof value === "number" && Number.isFinite(value);
const colorFilterPattern = /^(?:(?:grayscale|sepia|saturate|brightness|contrast)\(([-+]?\d*\.?\d+)(%|)?\)|hue-rotate\(([-+]?\d*\.?\d+)(deg|rad|grad|turn)\))(?:\s+(?:(?:grayscale|sepia|saturate|brightness|contrast)\(([-+]?\d*\.?\d+)(%|)?\)|hue-rotate\(([-+]?\d*\.?\d+)(deg|rad|grad|turn)\)))*$/;
function isColorFilter(value) { if (typeof value !== "string" || value.trim() === "" || value.trim() === "none") return false; if (!colorFilterPattern.test(value.trim())) return false; return (value.match(/[-+]?\d*\.?\d+/g) ?? []).every((item) => Number.isFinite(Number(item))); }
function argsToRect(image, args) { if (args.length === 8 && args.every(finite)) { const [sx, sy, sw, sh, dx, dy, dw, dh] = args; return sw > 0 && sh > 0 && dw > 0 && dh > 0 ? { sx, sy, sw, sh, dx, dy, dw, dh } : null; } if (args.length === 4 && args.every(finite)) { const [dx, dy, dw, dh] = args; const sw = image.naturalWidth ?? image.width; const sh = image.naturalHeight ?? image.height; return dw > 0 && dh > 0 ? { sx: 0, sy: 0, sw, sh, dx, dy, dw, dh } : null; } if (args.length === 2 && args.every(finite)) { const [dx, dy] = args; const sw = image.naturalWidth ?? image.width; const sh = image.naturalHeight ?? image.height; return sw > 0 && sh > 0 ? { sx: 0, sy: 0, sw, sh, dx, dy, dw: sw, dh: sh } : null; } return null; }
function defaultImmutableSource(image) { const imageBitmap = typeof ImageBitmap !== "undefined" && image instanceof ImageBitmap; const htmlImage = typeof HTMLImageElement !== "undefined" && image instanceof HTMLImageElement; return imageBitmap || htmlImage || image?.__V100_IMMUTABLE_SAMPLER__ === true; }

function createV100FilteredImageLayer({ createCanvas, maxBytes = DEFAULT_MAX_BYTES, maxEntries = DEFAULT_MAX_ENTRIES, immutableImagesOnly = true, isImmutableSource = defaultImmutableSource } = {}) {
  if (typeof createCanvas !== "function") throw new TypeError("createCanvas must be a function");
  if (!Number.isInteger(maxBytes) || maxBytes <= 0 || !Number.isInteger(maxEntries) || maxEntries <= 0 || typeof isImmutableSource !== "function") throw new RangeError("invalid filtered-image cache limits");
  const imageIds = new WeakMap(); let nextImageId = 1; let scratch = null; let work = null; let capacityWidth = 0; let capacityHeight = 0; let activeWidth = 0; let activeHeight = 0; let bytes = 0; let lastKey = null; let builds = 0; let hits = 0; let evictions = 0; let fallbacks = 0; let errors = 0; let drawCount = 0; let surfaceAllocations = 0; let resizes = 0; let reuses = 0;
  const release = () => { if (scratch) { try { scratch.width = 0; scratch.height = 0; } catch {} } scratch = null; work = null; capacityWidth = 0; capacityHeight = 0; activeWidth = 0; activeHeight = 0; bytes = 0; lastKey = null; };
  const fallback = (ctx, image, args) => { fallbacks += 1; return ctx.drawImage(image, ...args); };
  const fallbackOnceFactory = (ctx, image, args) => { let used = false; return () => { if (used) throw new Error("filtered-image fallback repeated"); used = true; return fallback(ctx, image, args); }; };
  const imageId = (image) => { let id = imageIds.get(image); if (!id) { id = nextImageId++; imageIds.set(image, id); } return id; };
  const round64 = (value) => Math.ceil(value / 64) * 64;
  const draw = (ctx, image, ...args) => {
    drawCount += 1; const fallbackOnce = fallbackOnceFactory(ctx, image, args); let mainBlitStarted = false; let fallbackStarted = false;
    const fallbackOriginal = () => { fallbackStarted = true; return fallbackOnce(); };
    try {
      if (immutableImagesOnly !== true || !image || (typeof image !== "object" && typeof image !== "function") || !isImmutableSource(image)) return fallbackOriginal();
      const filter = ctx.filter; if (!isColorFilter(filter)) return fallbackOriginal(); const attrs = typeof ctx.getContextAttributes === "function" ? ctx.getContextAttributes() : null; if (attrs?.colorSpace && attrs.colorSpace !== "srgb") return fallbackOriginal();
      if (ctx.globalCompositeOperation !== "source-over" || !finite(ctx.shadowBlur) || ctx.shadowBlur !== 0 || !finite(ctx.shadowOffsetX) || !finite(ctx.shadowOffsetY) || ctx.shadowOffsetX !== 0 || ctx.shadowOffsetY !== 0) return fallbackOriginal();
      const rect = argsToRect(image, args); if (!rect) return fallbackOriginal(); const matrix = ctx.getTransform(); if (![matrix.a, matrix.b, matrix.c, matrix.d, matrix.e, matrix.f].every(finite)) return fallbackOriginal();
      const corners = [[rect.dx, rect.dy], [rect.dx + rect.dw, rect.dy], [rect.dx, rect.dy + rect.dh], [rect.dx + rect.dw, rect.dy + rect.dh]].map(([x, y]) => [matrix.a * x + matrix.c * y + matrix.e, matrix.b * x + matrix.d * y + matrix.f]);
      const minX = Math.floor(Math.min(...corners.map(([x]) => x)) - 3); const minY = Math.floor(Math.min(...corners.map(([, y]) => y)) - 3); const maxX = Math.ceil(Math.max(...corners.map(([x]) => x)) + 3); const maxY = Math.ceil(Math.max(...corners.map(([, y]) => y)) + 3); const width = maxX - minX; const height = maxY - minY; const cost = width * height * 4;
      if (!Number.isSafeInteger(cost) || width <= 0 || height <= 0 || width > 4096 || height > 4096 || cost > maxBytes) return fallbackOriginal();
      const relativeX = matrix.a * rect.dx + matrix.c * rect.dy + matrix.e - minX; const relativeY = matrix.b * rect.dx + matrix.d * rect.dy + matrix.f - minY; const smooth = `${ctx.imageSmoothingEnabled}:${ctx.imageSmoothingQuality ?? ""}`; const sourceWidth = image.naturalWidth ?? image.width; const sourceHeight = image.naturalHeight ?? image.height; const sourceCurrent = typeof image.currentSrc === "string" ? image.currentSrc : ""; const key = JSON.stringify([imageId(image), sourceWidth, sourceHeight, sourceCurrent, rect.sx, rect.sy, rect.sw, rect.sh, rect.dw, rect.dh, matrix.a, matrix.b, matrix.c, matrix.d, width, height, relativeX, relativeY, filter, smooth]);
      if (lastKey === key && scratch && work) { hits += 1; reuses += 1; ctx.save(); try { const alpha = ctx.globalAlpha; ctx.setTransform(1, 0, 0, 1, 0, 0); ctx.filter = "none"; ctx.shadowBlur = 0; ctx.shadowOffsetX = 0; ctx.shadowOffsetY = 0; ctx.globalCompositeOperation = "source-over"; ctx.globalAlpha = alpha; mainBlitStarted = true; ctx.drawImage(scratch, 0, 0, activeWidth, activeHeight, minX, minY, width, height); } finally { ctx.restore(); } return; }
      if (lastKey !== null && lastKey !== key) evictions += 1;
      const requiredWidth = Math.max(capacityWidth, round64(width)); const requiredHeight = Math.max(capacityHeight, round64(height)); const requiredBytes = requiredWidth * requiredHeight * 4;
      if (!Number.isSafeInteger(requiredBytes) || requiredWidth > 4096 || requiredHeight > 4096 || requiredBytes > maxBytes) return fallbackOriginal();
      if (!scratch) { scratch = createCanvas(requiredWidth, requiredHeight); if (!scratch || typeof scratch.getContext !== "function") { release(); return fallbackOriginal(); } scratch.width = requiredWidth; scratch.height = requiredHeight; work = scratch.getContext("2d", { alpha: true, willReadFrequently: true, colorSpace: "srgb" }); const workAttrs = typeof work?.getContextAttributes === "function" ? work.getContextAttributes() : null; if (!work || (workAttrs?.colorSpace && workAttrs.colorSpace !== "srgb")) { release(); return fallbackOriginal(); } capacityWidth = requiredWidth; capacityHeight = requiredHeight; bytes = requiredBytes; surfaceAllocations += 1; } else if (requiredWidth !== capacityWidth || requiredHeight !== capacityHeight) { scratch.width = requiredWidth; scratch.height = requiredHeight; work = scratch.getContext("2d", { alpha: true, willReadFrequently: true, colorSpace: "srgb" }); const workAttrs = typeof work?.getContextAttributes === "function" ? work.getContextAttributes() : null; if (!work || (workAttrs?.colorSpace && workAttrs.colorSpace !== "srgb")) { release(); return fallbackOriginal(); } capacityWidth = requiredWidth; capacityHeight = requiredHeight; bytes = requiredBytes; resizes += 1; } else reuses += 1;
      const oldWidth = activeWidth; const oldHeight = activeHeight; activeWidth = width; activeHeight = height; work.save(); try { work.setTransform(1, 0, 0, 1, 0, 0); work.clearRect(0, 0, Math.max(oldWidth, activeWidth), Math.max(oldHeight, activeHeight)); work.beginPath(); work.rect(0, 0, activeWidth, activeHeight); work.clip(); work.setTransform(matrix.a, matrix.b, matrix.c, matrix.d, matrix.e - minX, matrix.f - minY); work.globalAlpha = 1; work.globalCompositeOperation = "source-over"; work.filter = filter; work.shadowBlur = 0; work.shadowOffsetX = 0; work.shadowOffsetY = 0; work.imageSmoothingEnabled = ctx.imageSmoothingEnabled; work.imageSmoothingQuality = ctx.imageSmoothingQuality; work.drawImage(image, rect.sx, rect.sy, rect.sw, rect.sh, rect.dx, rect.dy, rect.dw, rect.dh); } finally { work.restore(); }
      lastKey = key; builds += 1; ctx.save(); try { const alpha = ctx.globalAlpha; ctx.setTransform(1, 0, 0, 1, 0, 0); ctx.filter = "none"; ctx.shadowBlur = 0; ctx.shadowOffsetX = 0; ctx.shadowOffsetY = 0; ctx.globalCompositeOperation = "source-over"; ctx.globalAlpha = alpha; mainBlitStarted = true; ctx.drawImage(scratch, 0, 0, activeWidth, activeHeight, minX, minY, width, height); } finally { ctx.restore(); }
    } catch (error) { errors += 1; release(); if (mainBlitStarted || fallbackStarted) throw error; return fallbackOriginal(); }
  };
  const clear = () => release();
  const snapshot = () => ({ builds, hits, evictions, bytes, entries: lastKey === null ? 0 : 1, fallbacks, errors, drawCount, ownedSurfaces: scratch ? 1 : 0, immutableImagesOnly, maxBytes, maxEntries, surfaceAllocations, resizes, reuses, width: capacityWidth, height: capacityHeight, activeWidth, activeHeight });
  return Object.freeze({ draw, clear, snapshot });
}

export { createV100FilteredImageLayer };
