// Generated by scripts/build-takuya-battle-repaired-v2.py; source-bound geometry contract.
export const V100_TAKUYA_SPRITE_GEOMETRY = Object.freeze({
  "format": "nishijin-v100-takuya-repaired-motion-atlas",
  "version": 1,
  "path": "/art/v100/bosses/takuya-battle-repaired-v1.png",
  "cellWidth": 512,
  "cellHeight": 757,
  "columns": 6,
  "sourceWidth": 362,
  "sourceHeight": 724,
  "sourceOffset": {
    "x": 48,
    "y": 16
  },
  "anchorX": 0.447265625,
  "groundAnchorPixels": [
    604,
    609,
    607,
    606,
    617,
    608
  ],
  "states": [
    "idle",
    "walk-a",
    "walk-b",
    "attack-a",
    "attack-b",
    "hit"
  ],
  "visibleRects": [
    [
      91,
      142,
      433,
      604
    ],
    [
      102,
      153,
      415,
      609
    ],
    [
      95,
      153,
      417,
      607
    ],
    [
      106,
      47,
      482,
      606
    ],
    [
      75,
      263,
      406,
      617
    ],
    [
      43,
      191,
      378,
      608
    ]
  ],
  "sourceSha256": "05278f4dc66456baaed8fc85f69bbe752b7b8aeebace8ac8b92610db270230ee",
  "atlasSha256": "7baf14827f63faadbf7c05cd17d78edd735012a9def65904b50dae363d633419"
});
