// Generated by build-v100-r9-scenes.mjs from selected original scene masters.
export const V100_R9_SCENE_ASSETS=Object.freeze({
  "s03-cold-retrieval": {
    "path": "/art/v100/story-r9/cuts/s03-cold-retrieval.webp",
    "alt": "冷徹な回収班がタクヤと鎖を担架へ載せる。"
  },
  "s28-physical-stop": {
    "path": "/art/v100/story-r9/cuts/s28-physical-stop.webp",
    "alt": "武蔵とザキミヤが保護カバーを支え、隙間の奥の停止レバーへ手を伸ばす。"
  },
  "prologue-extinguisher-escape": {
    "path": "/art/v100/story-r9/cuts/prologue-extinguisher-escape.webp",
    "alt": "ババヤガが消火器を噴射し、クマが椅子を押し放して厨房の勝手口へ退く。"
  },
  "s01-nao-rescue": {
    "path": "/art/v100/story-r9/cuts/s01-nao-rescue.webp",
    "alt": "ナオが装甲車両で老人を救護し、運び終えたパイセンが隣でへたり込む。"
  },
  "s04-monkey-shutter": {
    "path": "/art/v100/story-r9/cuts/s04-monkey-shutter.webp",
    "alt": "モンキーが配線をつなぎ、開いたシャッターからクマが駅員を背負って運び出す。"
  },
  "s09-transfer-disconnect": {
    "path": "/art/v100/story-r9/cuts/s09-transfer-disconnect.webp",
    "alt": "いくらの指示したケーブルを抜く。救助映像の送信履歴は端末に残っている。"
  },
  "s11-oxygen-rescue": {
    "path": "/art/v100/story-r9/cuts/s11-oxygen-rescue.webp",
    "alt": "閉じた待機室の外で供給弁を回し、管を通した酸素で研究員たちを救う。"
  },
  "s22-zakimiya-holds-son": {
    "path": "/art/v100/story-r9/cuts/s22-zakimiya-holds-son.webp",
    "alt": "ザキミヤが息子の首を支えて抱き、妻と一緒に顔を見つめて泣き笑いする。"
  },
  "s14-train-couplers": {
    "path": "/art/v100/story-r9/cuts/s14-train-couplers.webp",
    "alt": "ＴＫＹが大口を押さえ、三人が赤い連結解除レバーを操作する。隣の青いブレーキ管は切らずに残す。"
  },
  "s17-chiha-baba-reunion": {
    "path": "/art/v100/story-r9/cuts/s17-chiha-baba-reunion.webp",
    "alt": "無傷の腕を確かめたチハがババヤガを抱きしめ、ババヤガも背中へ腕を回す。"
  },
  "s23-chiha-evidence-send": {
    "path": "/art/v100/story-r9/cuts/s23-chiha-evidence-send.webp",
    "alt": "チハ自身が証拠を送信する。三つの受信灯が点き、使い切った認証カードから細い煙が上がる。"
  },
  "s19-seven-second-crossing": {
    "path": "/art/v100/story-r9/cuts/s19-seven-second-crossing.webp",
    "alt": "別々の車線で装甲車両が敵車両を押しのけ、病院の白いバンが閉まりかけた遮断機を抜ける。"
  },
  "ending-chiha-baba-distance": {
    "path": "/art/v100/story-r9/cuts/ending-chiha-baba-distance.webp",
    "alt": "チハの伸ばした手をババヤガは少し避ける。それでも席を立たず、話を聞く。"
  },
  "ending-plates-and-karaage": {
    "path": "/art/v100/story-r9/cuts/ending-plates-and-karaage.webp",
    "alt": "パイセンに空の皿が重なり、ＴＫＹはまだ唐揚げを食べ、マヨは机の下で寝返りを打つ。"
  },
  "s10-rescue-surveillance": {
    "path": "/art/v100/story-r9/cuts/s10-rescue-surveillance.webp",
    "alt": "薬局の女性が手を振る映像と、パイセンたちが通った救助路が監視画面で繰り返されている。"
  },
  "s27-takuya-conditioning": {
    "path": "/art/v100/story-r9/cuts/s27-takuya-conditioning.webp",
    "alt": "救助路へ放たれたタクヤが警笛へ進路を変え、装置を壊す訓練記録が映る。"
  },
  "s30-three-samples": {
    "path": "/art/v100/story-r9/cuts/s30-three-samples.webp",
    "alt": "投薬管・血液・骨髄を別々の三容器に密閉し、回収箱の独立した溝へ収める。"
  }
});
