function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) deepFreeze(child);
  return Object.freeze(value);
}

export const V075_VISUAL_PROFILES = deepFreeze({
  ikura: {
    identityMaster: {
      path: "/art/v075/characters/reference/ikura-identity-master-r1.png",
      revision: "r1",
    },
    eventPortrait: {
      path: "/art/v075/characters/portraits/ikura-event-portrait-v4.webp",
      revision: "v4",
      focus: { x: 0.57, y: 0.28 },
      safeArea: { top: 0.02, right: 0.04, bottom: 0, left: 0.08 },
      minFacePixelsAt844x340: 38,
    },
    identityLock: [
      "warm-amber-eyes",
      "pink-twin-buns-and-voluminous-twin-tails",
      "black-amber-tactical-headset",
      "teal-pink-cropped-jacket-and-white-structured-top",
      "rugged-map-tablet",
    ],
  },
  crawler: {
    identityMaster: {
      path: "/art/v075/crawler/crawler-command-base-identity-r1.png",
      revision: "r1",
    },
    closed: {
      path: "/art/v075/crawler/crawler-command-base-closed-v1.png",
      revision: "v1",
    },
    open: {
      path: "/art/v075/crawler/crawler-command-base-open-v2.png",
      revision: "v2",
    },
    anchor: { x: 0.5, y: 0.9 },
    identityLock: [
      "right-facing-multi-axle-armored-command-base",
      "front-quarter-side-troop-door",
      "roof-turret-and-communications-array",
      "dark-weathered-armor-with-amber-lights",
    ],
  },
  enemyBase: {
    identityMaster: {
      path: "/art/v075/enemy-base/enemy-stronghold-identity-r1.png",
      revision: "r1",
    },
    intact: {
      path: "/art/v075/enemy-base/enemy-stronghold-intact-v2.png",
      revision: "v2",
    },
    anchor: { x: 0.5, y: 0.98 },
    identityLock: [
      "slender-asymmetrical-infected-communications-spire",
      "broken-sail-and-antenna-crown",
      "rusted-industrial-frame-and-organic-tendrils",
      "orange-infected-core-and-rooted-rubble-base",
    ],
  },
});

function unitProfile({
  unitId,
  combatKind,
  identityPath,
  identityRevision,
  eventPath,
  eventRevision,
  cardPath,
  battlePath,
  battleRevision,
  focus = { x: .5, y: .28 },
  identityLock,
}) {
  return {
    unitId,
    combatKind,
    identityMaster: {
      path: identityPath,
      revision: identityRevision,
    },
    eventPortrait: {
      path: eventPath,
      revision: eventRevision,
      focus,
      safeArea: { top: .02, right: .04, bottom: 0, left: .04 },
      minFacePixelsAt844x340: 34,
    },
    formationCard: {
      path: cardPath,
      revision: "r1",
      focus: { x: focus.x, y: Math.max(.2, focus.y) },
      requiredRead: ["face", "upper-body", "primary-weapon", "role-silhouette"],
    },
    personnelCard: {
      path: cardPath,
      revision: "r1",
      focus: { x: focus.x, y: Math.max(.2, focus.y) },
      requiredRead: ["face", "upper-body", "primary-weapon", "role-silhouette"],
    },
    battleSprite: {
      path: battlePath,
      revision: battleRevision,
    },
    identityLock,
  };
}

export const V080_UNIT_VISUAL_PROFILES = deepFreeze({
  brawler: unitProfile({
    unitId: "unit-paisen",
    combatKind: "brawler",
    identityPath: "/art/v060/characters/portraits/brawler-portrait-v2.webp",
    identityRevision: "v2",
    eventPath: "/art/v060/characters/portraits/brawler-portrait-v2.webp",
    eventRevision: "v2",
    cardPath: "/art/v080/characters/cards/brawler-formation-card-r1.webp",
    battlePath: "/art/v060/characters/legacy/brawler-battle-gutter-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .26 },
    identityLock: ["short-dark-hair", "bare-knuckle-frontliner", "weathered-street-tactical"],
  }),
  scout: unitProfile({
    unitId: "unit-hachi",
    combatKind: "scout",
    identityPath: "/art/v070/characters/reference/hachi-base-r2.png",
    identityRevision: "r2",
    eventPath: "/art/v070/characters/portraits/scout-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/scout-formation-card-r1.webp",
    battlePath: "/art/v070/characters/scout-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .24 },
    identityLock: ["light-scout-silhouette", "fast-melee-kit", "hachi-face-and-hair"],
  }),
  ranger: unitProfile({
    unitId: "unit-mizuchi",
    combatKind: "ranger",
    identityPath: "/art/v070/characters/reference/mizuchi-base-r3.png",
    identityRevision: "r3",
    eventPath: "/art/v070/characters/portraits/ranger-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/ranger-formation-card-r1.webp",
    battlePath: "/art/v070/characters/ranger-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .23 },
    identityLock: ["mizuchi-face-and-hair", "long-range-rifle", "slim-marksman-silhouette"],
  }),
  medic: unitProfile({
    unitId: "unit-nao",
    combatKind: "medic",
    identityPath: "/art/v070/characters/reference/nao-base-r1.png",
    identityRevision: "r1",
    eventPath: "/art/v070/characters/portraits/medic-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/medic-formation-card-r1.webp",
    battlePath: "/art/v070/characters/medic-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .23 },
    identityLock: ["nao-face-and-hair", "compact-medical-kit", "support-rifle"],
  }),
  brute: unitProfile({
    unitId: "unit-tatara",
    combatKind: "brute",
    identityPath: "/art/v070/characters/reference/tatara-base-r8.png",
    identityRevision: "r8",
    eventPath: "/art/v070/characters/portraits/brute-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/brute-formation-card-r1.webp",
    battlePath: "/art/v070/characters/brute-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .51, y: .24 },
    identityLock: ["tatara-face-and-hair", "oversized-sledgehammer", "heavy-breaker-silhouette"],
  }),
  gunner: unitProfile({
    unitId: "unit-raider",
    combatKind: "gunner",
    identityPath: "/art/v070/characters/reference/raider-base-r10.png",
    identityRevision: "r10",
    eventPath: "/art/v070/characters/portraits/gunner-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/gunner-formation-card-r1.webp",
    battlePath: "/art/v070/characters/gunner-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .23 },
    identityLock: ["raider-face-and-hair", "machine-gun", "suppression-shooter-silhouette"],
  }),
  "crazy-king": unitProfile({
    unitId: "unit-crazy-king",
    combatKind: "crazy-king",
    identityPath: "/art/v060/characters/portraits/crazy-king-portrait-v2.webp",
    identityRevision: "v2",
    eventPath: "/art/v060/characters/portraits/crazy-king-portrait-v2.webp",
    eventRevision: "v2",
    cardPath: "/art/v080/characters/cards/crazy-king-formation-card-r1.webp",
    battlePath: "/art/v060/characters/crazy-king-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .27 },
    identityLock: ["crazy-king-mask-and-hair", "chainsaw", "berserker-silhouette"],
  }),
  kumaverson: unitProfile({
    unitId: "unit-kumaverson",
    combatKind: "kumaverson",
    identityPath: "/art/v060/characters/portraits/kumaverson-portrait-v2.webp",
    identityRevision: "v2",
    eventPath: "/art/v060/characters/portraits/kumaverson-portrait-v2.webp",
    eventRevision: "v2",
    cardPath: "/art/v080/characters/cards/kumaverson-formation-card-r1.webp",
    battlePath: "/art/v060/characters/kumaverson-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .26 },
    identityLock: ["kumaverson-face-and-hair", "large-frontline-frame", "impact-weapon"],
  }),
  babayaga: unitProfile({
    unitId: "unit-babayaga",
    combatKind: "babayaga",
    identityPath: "/art/v060/characters/portraits/babayaga-portrait-v2.webp",
    identityRevision: "v2",
    eventPath: "/art/v060/characters/portraits/babayaga-portrait-v2.webp",
    eventRevision: "v2",
    cardPath: "/art/v080/characters/cards/babayaga-formation-card-r1.webp",
    battlePath: "/art/v060/characters/babayaga-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .22 },
    identityLock: ["babayaga-face-and-hair", "precision-rifle", "lean-sniper-silhouette"],
  }),
  guardian: unitProfile({
    unitId: "unit-gantetsu",
    combatKind: "guardian",
    identityPath: "/art/v070/characters/reference/gantetsu-base-r7.png",
    identityRevision: "r7",
    eventPath: "/art/v070/characters/portraits/guardian-portrait-v1.webp",
    eventRevision: "v1",
    cardPath: "/art/v080/characters/cards/guardian-formation-card-r1.webp",
    battlePath: "/art/v070/characters/guardian-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .5, y: .25 },
    identityLock: ["full-face-protective-gear", "shotgun-and-shield-kit", "heavy-guardian-frame"],
  }),
  engineer: unitProfile({
    unitId: "unit-monkey",
    combatKind: "engineer",
    identityPath: "/art/v080/characters/reference/monkey-identity-master-r1.png",
    identityRevision: "r1",
    eventPath: "/art/v080/characters/portraits/monkey-event-portrait-r1.webp",
    eventRevision: "r1",
    cardPath: "/art/v080/characters/cards/monkey-formation-card-r1.webp",
    battlePath: "/art/v070/characters/engineer-battle-v1.png",
    battleRevision: "v1",
    focus: { x: .54, y: .2 },
    identityLock: [
      "young-handsome-male-three-quarter-gaze",
      "layered-silver-hair-with-dark-roots",
      "charcoal-recon-tactical-kit",
      "suppressed-compact-carbine",
      "cyan-tripwire-trap-modules",
    ],
  }),
});
